import { StyleSheet } from 'react-native';
import { COLORS } from '@/constants/colors';

export const DARK = {
  bg: '#F4F1EA',
  text: '#2C2C2C',
  subtext: 'rgba(44,44,44,0.60)',
  border: 'rgba(0,0,0,0.08)',
  accent: '#4A6B53',
} as const;

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: DARK.bg,
  },
  safeArea: {
    flex: 1,
  },
  scrollContent: {
    flex: 1,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  greeting: {
    fontSize: 13,
    color: DARK.subtext,
    marginBottom: 4,
    fontWeight: '700',
    letterSpacing: 0.2,
  },
  title: {
    fontSize: 32,
    fontWeight: '900',
    color: DARK.text,
    letterSpacing: -0.6,
  },
  profileButton: {
    shadowColor: 'rgba(74,107,83,0.25)',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.35,
    shadowRadius: 12,
    elevation: 6,
  },
  profileImage: {
    width: 50,
    height: 50,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: '#FFFFFF',
  },
  scanStage: {
    flex: 1,
    overflow: 'hidden',
  },
  scanStageBg: {
    flex: 1,
  },
  scanStageTopBar: {
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 12,
    flexDirection: 'row',
    alignItems: 'flex-start',
    justifyContent: 'space-between',
  },
  scanStageTitleWrap: {
    gap: 6,
  },
  scanStageTitle: {
    color: DARK.text,
    fontSize: 26,
    fontWeight: '900',
    letterSpacing: -0.4,
  },
  scanStageSubtitle: {
    color: DARK.subtext,
    fontSize: 13,
    fontWeight: '700',
    letterSpacing: 0.15,
  },
  scanStageTopActions: {
    flexDirection: 'row',
    gap: 10,
  },
  topIconButton: {
    width: 38,
    height: 38,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(74,107,83,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(74,107,83,0.18)',
  },
  focusArea: {
    flex: 1,
    marginHorizontal: 12,
    borderRadius: 22,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: 'rgba(74,107,83,0.16)',
    backgroundColor: 'rgba(74,107,83,0.04)',
  },
  focusImage: {
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  focusPlaceholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  focusFrame: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  focusCornerWrap: {
    width: '72%',
    aspectRatio: 1,
  },
  focusCorner: {
    position: 'absolute',
    width: 32,
    height: 32,
    borderColor: 'rgba(44,44,44,0.45)',
  },
  focusCornerTL: {
    top: 0,
    left: 0,
    borderTopWidth: 3,
    borderLeftWidth: 3,
    borderTopLeftRadius: 6,
  },
  focusCornerTR: {
    top: 0,
    right: 0,
    borderTopWidth: 3,
    borderRightWidth: 3,
    borderTopRightRadius: 6,
  },
  focusCornerBL: {
    bottom: 0,
    left: 0,
    borderBottomWidth: 3,
    borderLeftWidth: 3,
    borderBottomLeftRadius: 6,
  },
  focusCornerBR: {
    bottom: 0,
    right: 0,
    borderBottomWidth: 3,
    borderRightWidth: 3,
    borderBottomRightRadius: 6,
  },
  scanBusyPill: {
    position: 'absolute',
    top: 14,
    left: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 999,
    backgroundColor: 'rgba(255,255,255,0.88)',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
  },
  scanBusyDot: {
    width: 8,
    height: 8,
    borderRadius: 99,
    backgroundColor: DARK.accent,
  },
  scanBusyText: {
    color: DARK.text,
    fontSize: 12,
    fontWeight: '900',
    letterSpacing: 0.2,
  },
  bottomTray: {
    paddingHorizontal: 16,
    paddingTop: 14,
    paddingBottom: 16,
  },
  modeRow: {
    flexDirection: 'row',
    alignSelf: 'center',
    backgroundColor: 'rgba(74,107,83,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(74,107,83,0.16)',
    borderRadius: 999,
    padding: 4,
    gap: 6,
    marginBottom: 14,
  },
  modePill: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 999,
  },
  modePillActive: {
    backgroundColor: 'rgba(74,107,83,0.14)',
  },
  modeText: {
    color: 'rgba(44,44,44,0.50)',
    fontSize: 13,
    fontWeight: '900',
  },
  modeTextActive: {
    color: DARK.accent,
  },
  controlsRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 6,
  },
  smallAction: {
    width: 54,
    height: 54,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(74,107,83,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(74,107,83,0.18)',
  },
  shutterOuter: {
    width: 86,
    height: 86,
    borderRadius: 999,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(74,107,83,0.14)',
    borderWidth: 3,
    borderColor: DARK.accent,
    shadowColor: DARK.accent,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.25,
    shadowRadius: 14,
    elevation: 10,
  },
  shutterInner: {
    width: 62,
    height: 62,
    borderRadius: 999,
    backgroundColor: DARK.accent,
  },
  section: {
    marginBottom: 32,
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 20,
    fontWeight: '900',
    color: DARK.text,
    letterSpacing: -0.2,
  },
  seeAllButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
  },
  seeAllText: {
    color: DARK.accent,
    fontWeight: '900',
    fontSize: 13,
    letterSpacing: 0.2,
  },
  guidesScroll: {
    paddingRight: 24,
    gap: 16,
  },
  guideCard: {
    width: 152,
    padding: 16,
    borderRadius: 24,
    justifyContent: 'space-between',
    height: 176,
  },
  guideCardBrand: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: 'rgba(74,107,83,0.18)',
    overflow: 'hidden',
    shadowColor: 'rgba(74,107,83,0.20)',
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.22,
    shadowRadius: 20,
    elevation: 8,
  },
  guideIconBrand: {
    width: 56,
    height: 56,
    borderRadius: 18,
    backgroundColor: 'rgba(74,107,83,0.10)',
    borderWidth: 1,
    borderColor: 'rgba(74,107,83,0.25)',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  guideTitleDark: {
    color: '#2C2C2C',
  },
  guideCountDark: {
    color: 'rgba(44,44,44,0.55)',
  },
  guideIconArt: {
    width: 44,
    height: 44,
    backgroundColor: 'transparent',
  },
  guideIcon: {
    width: 48,
    height: 48,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 12,
  },
  guideTitle: {
    fontSize: 16,
    fontWeight: '900',
    color: DARK.text,
    marginBottom: 4,
    letterSpacing: -0.1,
  },
  guideCount: {
    fontSize: 12,
    color: DARK.subtext,
    fontWeight: '800',
  },
  resultCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    padding: 16,
    marginBottom: 18,
    borderWidth: 1,
    borderColor: DARK.border,
  },
  resultHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  resultTitleRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  resultTitle: {
    fontSize: 14,
    fontWeight: '900',
    color: DARK.text,
    letterSpacing: 0.3,
  },
  rescanButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: 'rgba(74,107,83,0.10)',
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(74,107,83,0.22)',
  },
  rescanText: {
    color: DARK.accent,
    fontWeight: '900',
    fontSize: 12,
    letterSpacing: 0.2,
  },
  resultWarningRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    backgroundColor: '#FEF2F2',
    padding: 12,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(185, 28, 28, 0.12)',
    marginBottom: 12,
  },
  resultWarningText: {
    flex: 1,
    color: '#7F1D1D',
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 16,
  },
  resultBody: {
    gap: 10,
  },
  resultName: {
    fontSize: 16,
    fontWeight: '900',
    color: DARK.text,
    letterSpacing: -0.2,
  },
  resultMetaRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  pill: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(74,107,83,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(74,107,83,0.16)',
  },
  pillGood: {
    backgroundColor: '#ECFDF5',
  },
  pillBad: {
    backgroundColor: '#FFF7ED',
  },
  pillNeutral: {
    backgroundColor: '#EFF6FF',
  },
  pillText: {
    fontSize: 12,
    fontWeight: '900',
    color: DARK.subtext,
  },
  pillTextGood: {
    color: '#065F46',
  },
  pillTextBad: {
    color: '#9A3412',
  },
  pillTextNeutral: {
    color: '#1D4ED8',
  },
  resultNotes: {
    fontSize: 13,
    color: DARK.subtext,
    lineHeight: 18,
    fontWeight: '700',
  },
  bullets: {
    gap: 6,
    paddingTop: 4,
  },
  twoColRow: {
    flexDirection: 'row',
    gap: 10,
    paddingTop: 4,
  },
  infoTile: {
    flex: 1,
    backgroundColor: 'rgba(74,107,83,0.05)',
    borderRadius: 16,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: 'rgba(74,107,83,0.14)',
  },
  infoTileTitle: {
    fontSize: 11,
    fontWeight: '900',
    color: DARK.subtext,
    textTransform: 'uppercase',
    letterSpacing: 0.8,
    marginBottom: 6,
  },
  infoTileValue: {
    fontSize: 14,
    fontWeight: '900',
    color: DARK.text,
    letterSpacing: -0.2,
  },
  bulletsTitle: {
    fontSize: 12,
    fontWeight: '900',
    color: DARK.text,
    textTransform: 'uppercase',
    letterSpacing: 0.7,
  },
  bulletText: {
    fontSize: 13,
    color: DARK.subtext,
    lineHeight: 18,
    fontWeight: '700',
  },
  culturalFooter: {
    marginTop: 10,
    fontSize: 11,
    lineHeight: 16,
    color: 'rgba(44,44,44,0.50)',
    fontWeight: '800',
  },
  chatCard: {
    backgroundColor: '#FFFFFF',
    borderRadius: 22,
    padding: 16,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: DARK.border,
  },
  chatHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 6,
  },
  chatHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  chatTitle: {
    fontSize: 14,
    fontWeight: '900',
    color: DARK.text,
    letterSpacing: 0.3,
  },
  chatHeaderButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(74,107,83,0.10)',
    borderWidth: 1,
    borderColor: 'rgba(74,107,83,0.20)',
  },
  chatHeaderButtonText: {
    fontSize: 11,
    fontWeight: '800',
    color: DARK.text,
  },
  chatSubtitle: {
    fontSize: 12,
    color: DARK.subtext,
    fontWeight: '700',
    marginBottom: 12,
  },
  chatEmptyText: {
    fontSize: 12,
    color: DARK.subtext,
    fontWeight: '700',
  },
  chatErrorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: '#FEF2F2',
    borderRadius: 12,
    padding: 10,
    borderWidth: 1,
    borderColor: 'rgba(185, 28, 28, 0.12)',
    marginBottom: 10,
  },
  chatErrorText: {
    flex: 1,
    color: '#7F1D1D',
    fontSize: 12,
    fontWeight: '600',
    lineHeight: 16,
  },
  chatErrorDismiss: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 999,
    backgroundColor: 'rgba(185, 28, 28, 0.12)',
  },
  chatErrorDismissText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#7F1D1D',
  },
  chatMessages: {
    gap: 10,
    marginBottom: 10,
  },
  chatBubble: {
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(74,107,83,0.12)',
    maxWidth: '92%',
  },
  chatBubbleAssistant: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(74,107,83,0.06)',
  },
  chatBubbleUser: {
    alignSelf: 'flex-end',
    backgroundColor: 'rgba(74,107,83,0.12)',
    borderColor: 'rgba(74,107,83,0.22)',
  },
  chatBubbleText: {
    fontSize: 13,
    lineHeight: 18,
    fontWeight: '600',
    color: DARK.text,
  },
  chatSuggestionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  chatSuggestion: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(74,107,83,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
  },
  chatSuggestionText: {
    fontSize: 11,
    color: DARK.subtext,
    fontWeight: '700',
  },
  chatActionsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginLeft: 4,
  },
  chatActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingHorizontal: 12,
    height: 34,
    borderRadius: 999,
    backgroundColor: 'rgba(74,107,83,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
  },
  chatActionButtonSaved: {
    backgroundColor: 'rgba(74,107,83,0.12)',
    borderColor: 'rgba(74,107,83,0.28)',
  },
  chatActionText: {
    fontSize: 12,
    fontWeight: '800',
    color: DARK.text,
    letterSpacing: 0.2,
  },
  chatActionTextSaved: {
    color: COLORS.primary,
  },
  chatTimeoutRow: {
    marginTop: 10,
    paddingTop: 10,
    borderTopWidth: 1,
    borderTopColor: 'rgba(74,107,83,0.14)',
    gap: 10,
  },
  chatTimeoutText: {
    fontSize: 12,
    lineHeight: 16,
    fontWeight: '700',
    color: 'rgba(44,44,44,0.60)',
  },
  chatTimeoutActions: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  chatTimeoutButton: {
    paddingHorizontal: 14,
    height: 34,
    borderRadius: 999,
    backgroundColor: 'rgba(74,107,83,0.10)',
    borderWidth: 1,
    borderColor: 'rgba(74,107,83,0.20)',
    justifyContent: 'center',
  },
  chatTimeoutButtonText: {
    fontSize: 12,
    fontWeight: '900',
    color: DARK.text,
    letterSpacing: 0.2,
  },
  chatInputRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    backgroundColor: 'rgba(74,107,83,0.05)',
    borderRadius: 16,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
  },
  chatInput: {
    flex: 1,
    color: DARK.text,
    fontSize: 13,
    fontWeight: '600',
    minHeight: 36,
  },
  chatSendButton: {
    width: 36,
    height: 36,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: DARK.accent,
  },
  chatSendButtonDisabled: {
    opacity: 0.5,
  },
  collectionList: {
    gap: 16,
  },
  collectionCard: {
    flexDirection: 'row',
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    padding: 12,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(74,107,83,0.16)',
  },
  collectionImage: {
    width: 70,
    height: 70,
    borderRadius: 16,
  },
  collectionInfo: {
    flex: 1,
    marginLeft: 16,
  },
  collectionName: {
    fontSize: 16,
    fontWeight: '900',
    color: DARK.text,
    marginBottom: 4,
  },
  collectionDate: {
    fontSize: 12,
    color: DARK.subtext,
    marginBottom: 8,
    fontWeight: '700',
  },
  tagRow: {
    flexDirection: 'row',
    gap: 8,
  },
  tag: {
    backgroundColor: 'rgba(74,107,83,0.10)',
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(74,107,83,0.20)',
  },
  tagText: {
    fontSize: 10,
    color: DARK.accent,
    fontWeight: '900',
  },
});
